# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :nfss => {
        :box_name => "centos/7",
#        :box_version => "1804.02",
        :ip_addr => '192.168.56.10',
  },

  :nfsc => {
    :box_name => "centos/7",
#        :box_version => "1804.02",
    :ip_addr => '192.168.56.11',
},
}

Vagrant.configure("2") do |config|
   
    config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        SHELL
      end

    config.vm.base_mac = "525400c9c704"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    #config.vm.box_version = "1804.02"
    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
  
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
  
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
                    if needsController == true
                       vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                       boxconfig[:disks].each do |dname, dconf|
                           vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                       end
                    end
            end
  
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum install -y mdadm smartmontools hdparm gdisk
          SHELL
  
          
        end
    end
  end
  














# # -*- mode: ruby -*-
# # vi: set ft=ruby :
# home = ENV['HOME']
# ENV["LC_ALL"] = "en_US.UTF-8"

# ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
# Vagrant.configure(2) do |config|
#   config.vm.box = "centos/7"

#   # config.vm.provision "shell" do |s|
#   #   ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
#   #   s.inline = <<-SHELL
#   #     echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
#   #   SHELL
#   # end


#   config.vm.provider "virtualbox" do |v|
#     v.memory = 256
#     v.cpus = 1
#   end

#   config.vm.define "nfss" do |nfss|
#     nfss.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
#     nfss.vm.hostname = "nfss"
# #    nfss.vm.provision "shell", inline: $script   
# #    nfss.vm.provision "shell", path: "nfss_script.sh"
#     nfss.vm.provision "shell", inline: <<-SHELL
#     mkdir -p ~root/.ssh
#     cp ~vagrant/.ssh/auth* ~root/.ssh
#     SHELL

#   end

#   config.vm.define "nfsc" do |nfsc|
#     nfsc.vm.network "private_network", ip: "192.168.50.11", virtualbox__intnet: "net1"
#     nfsc.vm.hostname = "nfsc"
# #    nfsc.vm.provision "shell", path: "nfsc_script.sh"
#     nfsc.vm.provision "shell", inline: <<-SHELL
#     mkdir -p ~root/.ssh
#     cp ~vagrant/.ssh/auth* ~root/.ssh
#     SHELL
#   end
  
# end


